import { readFileSync } from "node:fs";
import { JSDOM } from "jsdom";
const dom = new JSDOM(`<!doctype html><div id="p"></div>`);
globalThis.window = dom.window; globalThis.document = dom.window.document;
globalThis.navigator = dom.window.navigator; globalThis.Element = dom.window.Element;
const abcjs = (await import("abcjs")).default;
const abc = readFileSync(process.argv[2], "utf8");
const [tune] = abcjs.renderAbc("p", abc, { add_classes: true });
tune.setTiming();
const t = (tune.noteTimings || []).filter((e) => e && e.left != null);
let idx = -1;
for (const e of t) if (e.measureStart) idx++;
console.log("abcjs가 편 마디 수(n):", idx + 1, "· 이벤트", t.length);
